name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:

  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t mon-image .

    - name: Test container
      run: |
        docker run -d -p 8083:80 --name test mon-image
        sleep 5
        curl http://localhost:8083

    - name: Login GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag image
      run: docker tag mon-image ghcr.io/${{ github.repository }}/mon-image:1.0

    - name: Push image
      run: docker push ghcr.io/${{ github.repository }}/mon-image:1.0
